=== sa1ntb3lts/liga-mx-xml/dtd/resultados.dtd
<!ELEMENT liga (jornada+)>
<!ELEMENT jornada (partido+)>

<!ELEMENT partido (fecha, equipo, equipo, estadio, estado)>
<!ATTLIST partido id ID #REQUIRED>

<!ELEMENT fecha (#PCDATA)>

<!ELEMENT equipo (nombre, goles, estadisticas?)>
<!ATTLIST equipo tipo (local | visitante) #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT goles (#PCDATA)>
<!ELEMENT estadisticas (tiros, faltas, tarjetas*)>
<!ELEMENT tiros (#PCDATA)>
<!ELEMENT faltas (#PCDATA)>
<!ELEMENT tarjetas (#PCDATA)>
<!ELEMENT estadio (#PCDATA)>
<!ELEMENT estado (#PCDATA)>

=== sa1ntb3lts/liga-mx-xml/xml/resultados-invalido.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partido SYSTEM "../dtd/resultados.dtd">
<partido id="914">
    <fecha>17-10-2024</fecha>

    <arbitro>Juan</arbitro>
    
    <equipo tipo="local">
        <nombre>America</nombre>
        <goles>2</goles>
        <estadisticas>
            <tiros>10</tiros>
            <faltas>8</faltas>
            <tarjetas>2</tarjetas>
        </estadisticas>
    </equipo>

    <equipo tipo="visitante">
        <nombre>Chivas</nombre>
        <goles>1</goles>
        <estadisticas>
            <tiros>7</tiros>
            <faltas>10</faltas>
            <tarjetas>3</tarjetas>
        </estadisticas>
    </equipo>
</partido>
